### ISSUE TITLE
When running example lorenz.py Residuals are not finite in the initial point.

### ISSUE THREAD

**Issue by bartolkaruza** [Ambrosys/glyph#41]
After doing a clean checkout of the glyph github project, I'm getting below error on running the Lorenz example.

`Python 3.6.4`

```
<deap.gp.PrimitiveSet object at 0x1069be320>
Traceback (most recent call last):
  File "examples/control/lorenz.py", line 137, in <module>
    main()
  File "examples/control/lorenz.py", line 78, in main
    app.run()
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/application.py", line 173, in run
    self.gp_runner.init(self.args.pop_size)
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/application.py", line 77, in init
    self._update()
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/application.py", line 87, in _update
    self._evals = self.assessment_runner(self.population)
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/assessment.py", line 53, in __call__
    for ind, fit in zip(invalid, fitnesses):
  File "examples/control/lorenz.py", line 47, in measure
    popt, rmse_opt = assessment.const_opt_leastsq(self.rmse, individual)
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/assessment.py", line 165, in const_opt_leastsq
    return const_opt(measure, individual, lsq=True, default_constants=default_constants, f_kwargs=f_kwargs, **kwargs)
  File "/Users/bartolkaruza/dev/proj/uva/glyph/glyph/assessment.py", line 152, in const_opt
    res = opt(fun=closure, x0=p0, **kwargs)
  File "/Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages/scipy/optimize/_lsq/least_squares.py", line 805, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.
```

Make init output
```
Bartols-MBP:glyph bartolkaruza$ make init
pip install -r requirements.txt
Requirement already satisfied: cache.py==0.1.3 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Collecting deap==1.0.2.post2 (from -r requirements.txt (line 9))
  Using cached deap-1.0.2.post2.tar.gz
  Requested deap==1.0.2.post2 from https://pypi.python.org/packages/5b/d7/a49d3dd7aa8cbaf2b1ac8f4d6495824c886fea8b3dac4a73dc4df94cad76/deap-1.0.2.post2.tar.gz#md5=ccf5ed7562e4d6236c9416e3b5a9d941 (from -r requirements.txt (line 9)), but installing version 1.0.2
Requirement already satisfied: dill==0.2.5 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: joblib==0.11 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: mpmath==0.19 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: numpy==1.11.2 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: pyyaml==3.12 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: pyzmq==16.0.2 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: scipy==0.19.0 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: sqlitedict==1.5.0 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: sympy==1.0 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: toolz==0.8.1 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from -r requirements.txt (line 19))
Installing collected packages: deap
  Found existing installation: deap 1.0.2
    Uninstalling deap-1.0.2:
      Successfully uninstalled deap-1.0.2
  Running setup.py install for deap ... done
Successfully installed deap-1.0.2
pip install -e .
Obtaining file:///Users/bartolkaruza/dev/proj/uva/glyph
Requirement already satisfied: deap in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: dill in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: numpy in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: pyyaml in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: scipy in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: sympy in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: toolz in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: pyzmq in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: cache.py==0.1.3 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: mpmath>=0.19 in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from sympy->pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: sqlitedict in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from cache.py==0.1.3->pyglyph==0.3.5+0.g2a2143f.dirty)
Requirement already satisfied: joblib in /Users/bartolkaruza/.pyenv/versions/3.6.4/lib/python3.6/site-packages (from cache.py==0.1.3->pyglyph==0.3.5+0.g2a2143f.dirty)
Installing collected packages: pyglyph
  Found existing installation: pyglyph 0.3.5+0.g2a2143f.dirty
    Uninstalling pyglyph-0.3.5+0.g2a2143f.dirty:
      Successfully uninstalled pyglyph-0.3.5+0.g2a2143f.dirty
  Running setup.py develop for pyglyph
Successfully installed pyglyph
```

**Comment by Ohjeah** [comment]
Thanks for the report. That behavior was introduced with scipy in version 1.0 and should be fixed with an upcoming pull request.
